name: CI

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: latest
          check-latest: true
          package-manager-cache: false
      - run: corepack enable && yarn && yarn build
      - run: yarn demo
        env:
          FORCE_COLOR: 1
